### ISSUE TITLE
Provide official Docker image

### ISSUE THREAD

**Issue by ngosang** [DRuggeri/alertmanager_gotify_bridge#12]
I have been using [this image](https://hub.docker.com/r/nathaneaston/alertmanager_gotify_bridge-docker) for a while but it has several issues:
* It's outdated
* It's not tagged properly so I can't know the version
* Is only available for AMD64 arch
* Is huge ~150 MB

I have fixed all these issues for me but I don't have time to maintain the fork. Maybe you can configure a GitHub action for doing it automatically. Example of GitHub actions => https://github.com/ngosang/urbackup-exporter

Dockerfile
```
FROM golang:1.17.0-alpine3.14 AS builder

RUN apk --no-cache add git

ARG VERSION
RUN go get github.com/DRuggeri/alertmanager_gotify_bridge@$VERSION

FROM alpine:3.14
COPY --from=builder /go/bin/alertmanager_gotify_bridge /usr/bin/alertmanager_gotify_bridge

ENTRYPOINT ["/usr/bin/alertmanager_gotify_bridge"]

# docker build -t alertmanager_gotify_bridge:v0.5.2-custom --build-arg VERSION=v0.5.2 .
```

docker-compose
```
  alertmanager_gotify_bridge:
    image: alertmanager_gotify_bridge:v0.5.2-custom
    container_name: alertmanager_gotify_bridge
    environment:
      - GOTIFY_TOKEN=xxxxxxx
      - GOTIFY_ENDPOINT=http://gotify:80/message
    ports:
      - 8080:8080
    restart: unless-stopped
```

@ndragon798  maybe is interested in helping.
