### ISSUE TITLE
Requesting example of implementation with Prometheus Grafana

### ISSUE THREAD

**Issue by sinicide** [DRuggeri/alertmanager_gotify_bridge#22]
Hi, hope this is the right way to ask this. I'm trying to use this in my Prometheus/Grafana Setup so that Grafana can send out Alerts to gotify. I have this alertmanager deployed, I can send the test message as your example shows to the /gotify_webhook endpoint. However I'm a little confused on how this integrates to Prometheus/Grafana for alerting.
I have configured prometheus with an alertmanager
```
  prometheus.yml: |
    global:
      scrape_interval: 15s
      scrape_timeout: 10s
      evaluation_interval: 1m
    
    alerting:
      alertmanagers:
      - scheme: https
        api_version: v1
        tls_config:
          insecure_skip_verify: true
        static_configs:
        - targets:
          - alertmanager-gotify.fqdn
```
Then in grafana, I try to setup a alertmanager configuration to the alertmanager endpoint, `alertmanager-gotify.fqdn` Note, I have a proxy that's redirecting port 443 -> 8080 and handling SSL.

I'm still new to alertmanager, but it looks like requests are sent to the following endpoint,
```
http://<alertmanager>:8080/api/v1/alerts
```
as I see the same path in prometheus. So I thought I needed to set `WEBHOOK_PATH: "/api/v1/alerts"` to match, but when I send a test payload from grafana it fails to unmarshal
```
2022/07/21 15:52:32 bridge: Unmarshal of request failed: json: cannot unmarshal array into Go value of type main.Notification
2022/07/21 15:52:32 
BEGIN passed data:
[{"labels":{"alertname":"TestAlert","instance":"Grafana"},"annotations":{"__value_string__":"[ metric='foo' labels={instance=bar} value=10 ]","description":"hello world","priority":"critical","summary":"hello world"},"startsAt":"2022-07-21T15:52:32.257789858Z","endsAt":"0001-01-01T00:00:00Z","generatorURL":"","UpdatedAt":"2022-07-21T15:52:32.257789858Z","Timeout":false}]
END passed data.
```

It seems like the payloads from grafana differ then what's expected from example. So I'm failing to understand how this is integrated, as it looks like some additional configuration changes need to be made on prometheus/grafana side to send a payload in a format it's expecting.

**Comment by pipip** [comment]
@sinicide I receive the same error message. Did you find a way to fix this?

**Comment by DRuggeri** [comment]
Not to leave you out in the dark, @sinicide - I just don't have experience setting up Grafana alerts. I use this only with alertmanager so far. Given the complaint in the code and the payload you shared above, it looks like Grafana is sending messages in the format of:
```
[
  {alert1...},
  {alert2...}
]
```

While, the Prometheus alertmanager instead sends them as:
```
{
  "alerts": [
    {alert1...},
    {alert2...}
  ]
}
```

In other words, alertmanager sends the payload as a JSON object with the array under the key `alerts` while payload you shared is sending only an array. This seems to go against the [example](https://grafana.com/docs/grafana/latest/alerting/manage-notifications/webhook-notifier/) provided in the Grafana documentation. It seems `alerts` is still an expected key and the payload is expected to be a JSON object.

**Comment by v4rakh** [comment]
Hi @DRuggeri , thanks for maintaining the bridge. Maybe I am not getting it, but I run into the same error with alertmanager v0.25.0 which seems to be the latest version.

My `prometheus.yml` looks like this

```yml
alerting:
  alertmanagers:
  - api_version: v2
    static_configs:
      - targets:
          - "alertmanager-gotify-bridge.fqdn"
```

I've set `WEBHOOK_PATH=/api/v2/alerts` in your bridge application.

So, alertmanager invokes a `POST` request to `http://alertmanager-gotify-bridge.fqdn/api/v2/alerts` and the OpenApi spec of alertmanager looks like [this](https://github.com/prometheus/alertmanager/blob/v0.25.0/api/v2/openapi.yaml). The actual request seems to be perfectly fine, but there's no `alerts` object, it also sends and array directly. Maybe this has changed?

This results in the very same error @sinicide has and I think that the bridge is actually expecting a wrong format here.

```shell
alertmanager_gotify_bridge  | 2023/01/22 23:13:25 bridge: Unmarshal of request failed: json: cannot unmarshal array into Go value of type main.Notification
alertmanager_gotify_bridge  | 2023/01/22 23:13:25
alertmanager_gotify_bridge  | BEGIN passed data:
alertmanager_gotify_bridge  | [{"annotations":{"description":"Instance is down.\nVALUE = 1\nLABELS: map[__name__:up instance:... job:...]","summary":"Instance down (instance ...)"},"endsAt":"2023-01-22T23:17:25.623Z","startsAt":"2023-01-22T23:13:25.623Z","generatorURL":"http://.../graph?g0.expr=up+%3E%3D+1\u0026g0.tab=1","labels":{"alertname":"instance_checks","instance":"...","job":"...","severity":"critical"}}]
alertmanager_gotify_bridge  | END passed data.
```

Then alertmanager has the following error obviously.

`prometheus    | ts=2023-01-22T23:19:25.629Z caller=notifier.go:532 level=error component=notifier alertmanager=http://alertmanager-gotify-bridge.fqdn/api/v2/alerts count=1 msg="Error sending alert" err="bad response status 400 Bad Request"`

**Comment by v4rakh** [comment]
@sinicide I've not tried to connect to Grafana, but actually configured it in the same way and ran into the same "error", but when I added the following to my `alertmanager.yml`  then everything started working, thanks for maintaining it @DRuggeri .

```yml
receivers:
    - name: 'default-receiver'
      webhook_configs:
        - url: http://gotify-bridge-fqdn/gotify_webhook
```
