### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by yanne057** [DRuggeri/alertmanager_gotify_bridge#35]
I have Prometheus, Alertmanager and Gotify setup in Docker. But when a alert should be sent out to gotify i dont get a message.  Has someone got an idea what i'm doing wrong?

When i look at the logs of Alertmanager i get the following error:
```
ts=2024-09-09T11:26:58.533Z caller=notify.go:848 level=warn component=dispatcher receiver=gotify integration=webhook[0] aggrGroup="{}:{alertname=\"MonitorDown\", severity=\"warning\"}" msg="Notify attempt failed, will retry later" attempts=1 err="Post \"<redacted>\": dial tcp 127.0.0.1:9080: connect: connection refused"
```

This is my docker-compose.yml:
```
  alertmanager_gotify_bridge:
    image: druggeri/alertmanager_gotify_bridge:2.3.1
    container_name: alertmanager_gotify_bridge
    networks:
      - traefik
    environment:
      - GOTIFY_TOKEN=TOKEN
      - GOTIFY_ENDPOINT=https://gotify.domain/message
    volumes:
      - ./bridge_alertmanager_gotify_templates:/./templates
    ports:
      - 9080:9080
    restart: unless-stopped
    command:
      - '--port=9080'
```

And i have configured the following in the alertmanager.yml
```
receivers:
  - name: 'gotify'
    webhook_configs:
      - url: http://127.0.0.1:9080/gotify_webhook?token=TOKEN
        send_resolved: true
```
